<?php
/**
 * AccountSettingsEmailNotificationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Zoom\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zoom API
 *
 * The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applicatixons on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developersupport@zoom.us
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zoom\Api;

use PHPUnit\Framework\TestCase;

/**
 * AccountSettingsEmailNotificationTest Class Doc Comment
 *
 * @category    Class
 * @description Account Settings: Notification.
 * @package     Zoom\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AccountSettingsEmailNotificationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountSettingsEmailNotification"
     */
    public function testAccountSettingsEmailNotification()
    {
    }

    /**
     * Test attribute "cloud_recording_avaliable_reminder"
     */
    public function testPropertyCloudRecordingAvaliableReminder()
    {
    }

    /**
     * Test attribute "jbh_reminder"
     */
    public function testPropertyJbhReminder()
    {
    }

    /**
     * Test attribute "cancel_meeting_reminder"
     */
    public function testPropertyCancelMeetingReminder()
    {
    }

    /**
     * Test attribute "low_host_count_reminder"
     */
    public function testPropertyLowHostCountReminder()
    {
    }

    /**
     * Test attribute "alternative_host_reminder"
     */
    public function testPropertyAlternativeHostReminder()
    {
    }

    /**
     * Test attribute "schedule_for_reminder"
     */
    public function testPropertyScheduleForReminder()
    {
    }
}
