<?php
/**
 * PhoneApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applicatixons on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developersupport@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PhoneApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PhoneApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountCallLogs
     *
     * Get Account's Call Logs.
     *
     */
    public function testAccountCallLogs()
    {
    }

    /**
     * Test case for assignCallingPlan
     *
     * Assign Calling Plan to a User.
     *
     */
    public function testAssignCallingPlan()
    {
    }

    /**
     * Test case for assignPhoneNumber
     *
     * Assign Phone Number to User.
     *
     */
    public function testAssignPhoneNumber()
    {
    }

    /**
     * Test case for changeMainCompanyNumber
     *
     * Change Main Company Number.
     *
     */
    public function testChangeMainCompanyNumber()
    {
    }

    /**
     * Test case for getPhoneNumberDetails
     *
     * Get Phone Number Details.
     *
     */
    public function testGetPhoneNumberDetails()
    {
    }

    /**
     * Test case for listAccountPhoneNumbers
     *
     * List Phone Numbers.
     *
     */
    public function testListAccountPhoneNumbers()
    {
    }

    /**
     * Test case for listCallingPlans
     *
     * List Calling Plans.
     *
     */
    public function testListCallingPlans()
    {
    }

    /**
     * Test case for listPhoneUsers
     *
     * List Phone Users.
     *
     */
    public function testListPhoneUsers()
    {
    }

    /**
     * Test case for phoneUser
     *
     * Get User's Profile.
     *
     */
    public function testPhoneUser()
    {
    }

    /**
     * Test case for phoneUserCallLogs
     *
     * Get User's Call Logs.
     *
     */
    public function testPhoneUserCallLogs()
    {
    }

    /**
     * Test case for phoneUserRecordings
     *
     * Get User's Recordings.
     *
     */
    public function testPhoneUserRecordings()
    {
    }

    /**
     * Test case for phoneUserSettings
     *
     * Get User's Settings.
     *
     */
    public function testPhoneUserSettings()
    {
    }

    /**
     * Test case for phoneUserVoiceMails
     *
     * Get User's Voicemails.
     *
     */
    public function testPhoneUserVoiceMails()
    {
    }

    /**
     * Test case for unassignCallingPlan
     *
     * Unassign User's Calling Plan.
     *
     */
    public function testUnassignCallingPlan()
    {
    }

    /**
     * Test case for unassignPhoneNumber
     *
     * Unassign User's Phone Number.
     *
     */
    public function testUnassignPhoneNumber()
    {
    }

    /**
     * Test case for updateUserProfile
     *
     * Update User's Profile.
     *
     */
    public function testUpdateUserProfile()
    {
    }
}
